import { useState } from 'react'
// import './Card.css'

function MetricCard({ title, value, change, period, isPositive }) {
  return (
    <div className="metric-card">
      <div className="metric-title">{title}</div>
      <div className="metric-value">{value}</div>
      <div className="metric-change">
        Since Last {period}
        <span className={isPositive ? 'change-positive' : 'change-negative'}>
          {isPositive ? '↑' : '↓'} {Math.abs(change)}%
        </span>
      </div>
    </div>
  )
}

function Card() {
  const [activeTab, setActiveTab] = useState('Revenue')

  return (
    <div className="dashboard">
      <div className="metrics-container">
        <MetricCard
          title="Total Managed Clients"
          value="5.80K"
          change={28.4}
          period="Month"
          isPositive={true}
        />
        <MetricCard
          title="Total HNI Clients"
          value="2.00K"
          change={-28.4}
          period="Month"
          isPositive={false}
        />
        <MetricCard
          title="Total AUM"
          value="500.8Cr"
          change={28.4}
          period="Year"
          isPositive={true}
        />
        <div className="metric-card">
          <div className="metric-title">Overall Target Achievement</div>
          <div className="metric-value">76.86%</div>
          <div style={{ width: '100%', backgroundColor: '#eee', borderRadius: '10px' }}>
            <div
              style={{
                width: '79%',
                height: '8px',
                backgroundColor: '#ff6b6b',
                borderRadius: '10px'
              }}
            />
          </div>
        </div>
        <div className="metric-card">
          <div className="metric-title">Client Churn Rate</div>
          <div className="gauge-chart">
            <div className="gauge-fill" />
          </div>
          <div style={{ textAlign: 'center', marginTop: '10px' }}>
            Active Clients: 93%
          </div>
        </div>
      </div>

      <div className="chart-section">
        <div className="chart-container">
          <div className="chart-header">
            <div className="tab-group">
              {['Revenue', 'AUM', 'Net Sales'].map(tab => (
                <div
                  key={tab}
                  className={`tab ${activeTab === tab ? 'active' : ''}`}
                  onClick={() => setActiveTab(tab)}
                >
                  {tab}
                </div>
              ))}
            </div>
            <select className="year-selector">
              <option>2021</option>
              <option>2022</option>
              <option>2023</option>
            </select>
          </div>
          <div>
            Chart placeholder - Add your preferred charting library
          </div>
        </div>

        <div className="insights-container">
          <div className="insights-title">
            <span>Branch Insights</span>
            <select className="year-selector">
              <option>Mutual Fund</option>
              <option>Insurance</option>
            </select>
          </div>
          <div className="insight-card">
            While your peers are averaging 15 policy sales, your current sales stand at 12.
          </div>
          <div className="insight-card">
            You have the potential to increase your revenue by ₹50,000 to match the average of ₹150,000 generated by your peers.
          </div>
        </div>
      </div>
    </div>
  )
}

export default Card