import "./FinancialDashboard.css"
import Chart from "./Chart"
import GradientProgressBar from "./GradientProgressBar"
import SemiCircleGauge from "./SemiCircleGauge"

const FinancialDashboard = () => {
  


  return (
    <div>
      {/* Top Cards */}
      <div className="metrics-row">
        <div className="metric-card">
          <div className="metric-title">Total Managed Clients</div>
          <div className="metric-value">5.80K</div>
          <div className="metric-footer">
            <span className="metric-period">Since Last Month</span>
            <span className="metric-change positive">28.4% ↑</span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-title">Total HNI Clients</div>
          <div className="metric-value">2.00K</div>
          <div className="metric-footer">
            <span className="metric-period">Since Last Month</span>
            <span className="metric-change negative">28.6% ↓</span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-title">Total AUM</div>
          <div className="metric-value">500.8Cr</div>
          <div className="metric-footer">
            <span className="metric-period">Since Last Year</span>
            <span className="metric-change positive">28.4% ↑</span>
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-title">Overall Target Achievement</div>
          <div className="metric-value">76.86%</div>
          <div className="metric-footer">
          <GradientProgressBar progress={19} />
          </div>
        </div>

        <div className="metric-card">
          <div className="metric-title">Client Churn Rate</div>
          <SemiCircleGauge percentage={93} />
        </div>
      </div>


      {/* Bottom Section */}
      <div className="dashboard-bottom">     
        <div className="chart-section">       
         <Chart />     
        </div>

        <div className="insights-panel">
          <div className="insights-header">
            <h3>Branch Insights</h3>
            {/* <div className="dropdown">
              <select>
                <option>Mutual Fund</option>
                <option>Equity</option>
                <option>Bonds</option>
              </select>
            </div> */}
          </div>

          <div className="insights-content">
            <p>While your peers are averaging 15 policy sales, your current sales stand at 12.</p>
            <p>
              You have the potential to increase your revenue by ₹50,000 to match the average of ₹150,000 generated by
              your peers.
            </p>
              <>
              <span className="highlights" >Mutual Fund</span>
              <p>
              While your peers are averaging 15 policy sales, your current sales stand at 12.
              </p>
             </>
            
           
          </div>
        </div>
      </div>
    </div>
  )
}

export default FinancialDashboard

